# Model information refresh interval (in seconds)
refresh_interval: 300  # 5 minutes

# List of LLM backends
backends:
  - name: "local-llama"
    url: "http://localhost:8000"
    auth:
      type: "basic"
      username: "admin"
      password: "secret123"
  
  - name: "ollama-server"
    url: "http://ollama:11434"
    # No auth needed
  
  - name: "openai-proxy"
    url: "http://openai-proxy:3000"
    auth:
      type: "bearer"
      token: "sk-..."
  
  - name: "anthropic-proxy"
    url: "http://anthropic-proxy:4000"
    auth:
      type: "header"
      name: "X-API-Key"
      value: "ant-..."
